name: Build and Deploy Frontend

on:
  workflow_dispatch:
  push:
    branches: [main]

# on:
#   push:
#     branches: [main]
#     paths:
#       - 'src/**'
#       - 'public/**'
#       - 'Dockerfile'
#       - 'package.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image (backend)
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: |
            rafli27/react-frontend:latest

      # - name: Build Docker image
      #   run: |
      #     docker build -t rafli27/react-frontend:latest .

      # - name: Push to Docker Hub
      #   run: |
      #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      #     docker push rafli27/react-frontend:latest

      # - name: Deploy to VM
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.VM_HOST }}
      #     username: ${{ secrets.VM_USERNAME }}
      #     key: ${{ secrets.VM_SSH_KEY }}
      #     script: |
      #       cd /opt/app-infra
      #       docker pull rafli27/react-frontend:latest
      #       docker-compose up -d --no-deps frontend
      #       echo "✅ Frontend deployed successfully!"
