name: Build and Deploy Frontend

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=react-login-app
            -Dsonar.organization=rafli277
            -Dsonar.sources=src
            -Dsonar.language=js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

      - name: Build React App
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rafli27/react-frontend:latest

      # - name: Deploy to Server
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       cd /opt/repo-infra
      #       #login Dockerhub
      #       echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
      #       # Pull image
      #       docker pull rafli27/react-frontend:latest
      #       # Restart frontend container
      #       docker ps -a
      #       docker-compose up -d --no-deps frontend
      #       # cek log
      #       #docker-compose logs -f frontend --tail=10
      #       #cleanup old images (keep 1)
      #       cd /opt/repo-infra
      #       ./cleanup-fe.sh
